async page => {
 const errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const checks=[];
 const check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
 const state=()=>page.evaluate(()=>JSON.parse(window.firetruckTouch.telemetry));
 const command=async(action,args={})=>{await page.evaluate(({action,args})=>{Object.assign(window.firetruckQA,args,{action});window.firetruckQA.sequence++;},{action,args});await page.waitForTimeout(220);};
 await page.setViewportSize({width:1280,height:800});
 await page.goto('http://localhost:8064/?qa=travel&review=smooth-road');
 await page.getByRole('button',{name:'Start',exact:true}).click();
 await page.waitForFunction(()=>window.firetruckTouch?.telemetry && !JSON.parse(window.firetruckTouch.telemetry).loading,{},{timeout:60000});
 await page.screenshot({path:'output/playwright/browser-new-room.png'});
 await command('pose',{x:0,z:-64});
 const before=(await state()).truck_position;
 await page.keyboard.press('r');
 await page.waitForTimeout(250);
 const after=(await state()).truck_position;
 check(Math.hypot(after[0]-before[0],after[1]-before[1])<.2,'R does not recover or move the truck');
 await command('start_train');
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).north_exit_open,{},{timeout:6000});
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition_clock>21,{},{timeout:26000});
 await page.screenshot({path:'output/playwright/browser-new-race-title.png'});
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='race_track'&&!t.transition;},{},{timeout:12000});
 await command('pose',{x:-4,z:-54,value:.85});
 await command('drive_race');
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.lap_running&&t.race_checkpoint===0&&t.lap_time>20;},{},{timeout:55000});
 await page.screenshot({path:'output/playwright/browser-new-bridge-driving.png'});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).last_lap>0,{},{timeout:22000});
 const lap=await state();
 check(lap.last_lap>35&&lap.race_drive_frames>2000,'Ordinary truck acceleration and steering complete the winding circuit');
 check(lap.surface_error<.08&&lap.flat_height_step<.005,'Actual browser motion follows the bridge within 8 cm and flat asphalt within 5 mm per frame');
 await command('stop_race_drive');
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 const began=Date.now();
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='maple_bay'&&!t.transition;},{},{timeout:6000});
 check(Date.now()-began<4000,'The return carpet swap finishes in under four seconds including telemetry delay');
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='race_track'&&!t.transition;},{},{timeout:6000});
 check(errors.length===0,'The updated WebGL build has no console errors');
 return {checks,lap:{seconds:lap.last_lap,surface_error:lap.surface_error,flat_height_step:lap.flat_height_step,frames:lap.race_drive_frames},errors};
}
