async page => {
 const errors=[],checks=[],captures=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const state=()=>page.evaluate(()=>JSON.parse(window.firetruckTouch.telemetry));
 const check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
 const command=async(action,args={})=>{
  await page.evaluate(({action,args})=>{Object.assign(window.firetruckQA,args,{action});window.firetruckQA.sequence++;},{action,args});
  await page.waitForTimeout(240);
 };
 const capture=async(phase,time)=>{
  const field=phase==='intro'?'intro_clock':'transition_clock';
  await page.waitForFunction(({field,time})=>JSON.parse(window.firetruckTouch.telemetry)[field]>=time,{field,time},{timeout:35000});
  const path=`output/playwright/throw-browser-${phase}-${String(time).replace('.','-')}.png`;
  await page.screenshot({path});
  captures.push({phase,time:(await state())[field],path});
 };
 await page.setViewportSize({width:1280,height:800});
 await page.goto('http://localhost:8064/?qa=travel&review=throw-and-cab');
 await page.waitForFunction(()=>window.firetruckTouch?.telemetry && document.querySelector('#progress').getAttribute('aria-valuenow')==='100',{},{timeout:60000});
 check((await state()).intro_clock===0,'The faster rollout still waits for Start');
 await page.getByRole('button',{name:'Start',exact:true}).click();
 await page.waitForFunction(()=>!JSON.parse(window.firetruckTouch.telemetry).loading);
 for(const time of [.25,.65,1.2,2.2,22.4,23.8]) await capture('intro',time);
 await page.waitForFunction(()=>!JSON.parse(window.firetruckTouch.telemetry).intro,{},{timeout:5000});
 await page.waitForTimeout(400);
 await page.screenshot({path:'output/playwright/throw-browser-ringing-a.png'});
 await page.waitForTimeout(180);
 await page.screenshot({path:'output/playwright/throw-browser-ringing-b.png'});
 check(!(await state()).talking,'The icon rings before the dispatcher speaks');
 await command('start_train');
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).north_exit_open,{},{timeout:5000});
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 for(const time of [1.1,1.85,2.05,2.4,3.1,4.6,22.2,23.4,24.3,25.7]) await capture('race',time);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='race_track'&&!t.transition;},{},{timeout:5000});
 await page.screenshot({path:'output/playwright/throw-browser-race-control.png'});
 await page.keyboard.down('s');
 await page.waitForTimeout(400);
 await page.keyboard.up('s');
 check((await state()).speed>.5,'The Motorway handover restores responsive truck control');
 const began=Date.now();
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 for(const time of [.7,1.1,1.3,1.85,2.4,2.7]) await capture('return',time);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='maple_bay'&&!t.transition;},{},{timeout:5000});
 const returnMs=Date.now()-began;
 check(returnMs<4000,'The continuous lift-and-unroll return keeps the short travel duration');
 await page.screenshot({path:'output/playwright/throw-browser-return-control.png'});
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 await capture('revisit',1.1);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='race_track'&&!t.transition;},{},{timeout:5000});
 check((await state()).transition_clock<3,'Later Motorway visits also use the short uninterrupted swap');
 check(errors.length===0,'The warmed carpet fade, ringing icon and both swaps have no browser/game console errors');
 return {checks,captures,returnMs,errors};
}
