async page => {
 const errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const checks=[],captures=[];
 const check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
 const state=()=>page.evaluate(()=>JSON.parse(window.firetruckTouch.telemetry));
 const command=async(action,args={})=>{
  await page.evaluate(({action,args})=>{Object.assign(window.firetruckQA,args,{action});window.firetruckQA.sequence++;},{action,args});
  await page.waitForTimeout(250);
 };
 const capture=async(phase,time)=>{
  const field=phase==='maple'?'intro_clock':'transition_clock';
  await page.waitForFunction(({field,time})=>JSON.parse(window.firetruckTouch.telemetry)[field]>=time,{field,time},{timeout:12000});
  const path=`output/playwright/motorway-browser-${phase}-${String(time).replace('.','-')}.png`;
  await page.screenshot({path});
  captures.push({phase,time:(await state())[field],path});
 };
 await page.setViewportSize({width:1280,height:800});
 await page.goto('http://localhost:8064/?qa=travel&review=motorway-race-club');
 await page.waitForFunction(()=>window.firetruckTouch?.telemetry && document.querySelector('#progress').getAttribute('aria-valuenow')==='100',{},{timeout:60000});
 await page.waitForTimeout(1000);
 check((await state()).intro_clock===0,'The mat and camera wait for Start');
 await page.getByRole('button',{name:'Start',exact:true}).click();
 await page.waitForFunction(()=>!JSON.parse(window.firetruckTouch.telemetry).loading);
 for(const time of [2.3,4.8]) await capture('maple',time);
 await command('pose',{x:0,z:12});
 await command('start_train');
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).north_exit_open,{},{timeout:10000});
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 for(const time of [.8,3.5,5.9,9.8,13.7,14.3,17,20.4,21,22.3,23,25.4]) await capture('race',time);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='race_track'&&!t.transition;},{},{timeout:5000});
 await page.screenshot({path:'output/playwright/motorway-browser-clean-arrival.png'});
 await page.keyboard.down('s');
 await page.waitForTimeout(400);
 await page.keyboard.up('s');
 check((await state()).speed>.5,'The first Motorway tour returns responsive truck control');
 await command('pose',{x:-2,z:-54});
 await command('pose',{x:2,z:-54});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).lap_running,{},{timeout:5000});
 check((await state()).race_checkpoint===1,'Crossing Start begins an ordered lap');
 await command('pose',{x:0,z:-72.5});
 check((await state()).lap_running,'A lap survives 12 metres of grass beyond the asphalt edge');
 await page.screenshot({path:'output/playwright/motorway-browser-grass-allowed.png'});
 await command('pose',{x:0,z:-74.5});
 const canceled=await state();
 check(!canceled.lap_running && canceled.lap_time===0,'Going beyond the 13-metre allowance cancels and resets the timer');
 await page.screenshot({path:'output/playwright/motorway-browser-silent-cancel.png'});
 await command('pose',{x:-2,z:-54});
 await command('pose',{x:2,z:-54});
 check((await state()).lap_running && (await state()).race_checkpoint===1,'The next Start crossing begins another attempt after cancellation');
 const began=Date.now();
 await command('pose',{x:0,z:-74});
 await command('pose',{x:0,z:-83});
 await page.waitForFunction(()=>JSON.parse(window.firetruckTouch.telemetry).transition);
 for(const time of [.7,2.2]) await capture('return',time);
 await page.waitForFunction(()=>{const t=JSON.parse(window.firetruckTouch.telemetry);return t.world==='maple_bay'&&!t.transition;},{},{timeout:5000});
 const returnMs=Date.now()-began;
 check(returnMs<4000,'The return uses the short carpet swap');
 check(errors.length===0,'The browser reports no game or console errors');
 return {checks,captures,returnMs,errors};
}
